### ISSUE TITLE
Radiance recipe id?

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/honeybee-json#1]
Hi, I'm starting to give a go a adding to_json and from_json class methods to honeybee core daylight recipes. I noticed that Solar Access has an id of "0" and Point in Time Grid Based and id of "1". Is there a list of the right id's to add anywhere in the repo or is it first recipe come first served in terms of id?

**Comment by mostaphaRoudsari** [comment]
Hi @AntoineDao. There is no list of ids. I started with ids during the hackathon to have a quick solution for two different types. We can put one together or we can change this to name and have a more proper naming which will also be human readable and extendable. 

```python
{
'name': 'point-in-time-grid-based',
...
}
{
'name': 'annual-grid-based',
... # and so on
}
```
Let us know what you come up with and we will make that the standard practice. We should also consider that this services can end up being more than daylight analysis.

**Comment by AntoineDao** [comment]
I reckon using name instead of id is probably a good idea. I'm also thinking it might be worth adding guuid to the recipe json file so that we can differentiate between multiple runs sent to a server.

**Comment by mostaphaRoudsari** [comment]
I'm not sure what's the best practice. That can also work. Currently uuid is generated on the server side by celery [once a job is submitted to a worker and returned to the user](https://github.com/ladybug-tools/honeybee-server-daylight/blob/727c301e18bea6371b9d85c4d25c7ad159c457b9/honeybee-worker/tasks.py#L33). I like to keep it on the server side as we can also manage the parent uuid and the child uuid all together. Otherwise we have to map the local uuid with the one generated on the server side.

**Comment by AntoineDao** [comment]
Nice one. Wasn't aware celery assigned uuid to processes. Makes sense really.

**Comment by AntoineDao** [comment]
stale and probably solved.
